# Generated by Django 5.1.1 on 2024-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando Autorização'), ('EM_VISITA', 'Em visita'), ('FINALIZADO', 'Visita Finalizada')], default='AGUARDANDO', max_length=10, verbose_name='status'),
        ),
    ]
