# Generated by Django 5.1.1 on 2024-11-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('andar', models.IntegerField()),
                ('garagem', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'db_table': 'Apartamento',
            },
        ),
    ]
